### ISSUE TITLE
Algorithms Study result 

### ISSUE THREAD

**Issue by hassanabidpk** [DjangoGirlsSeoul/studygroup_2016#17]
`let members = 12`
`let day = "Sunday"`
`let duration = "2 hours"`
`let repetition = "once a month"`
`let  anyQuestion: String?`
`let firstAlgorithm = "HeapSort"`
## // 아마 스터디 #bluebook_group 랑 같이 진행 할것같아요 !

If you have question/feedback post here!

**Comment by aweekj** [comment]
bluebook_group 이랑 같이 진행한다는게 같은 시간에 한다는 뜻인가요? ;(

**Comment by hassanabidpk** [comment]
@AWEEKJ  한달에 한번 하니까 그리고 bluebook 스터디 모임 전/후에 할거 예장입니다 @downy158

**Comment by mingrammer** [comment]
repetition은 오프라인 주기죠? 온라인주기는 1주일 맞죠?

**Comment by hassanabidpk** [comment]
Thanks for the feedback!
