### ISSUE TITLE
TASK 1 : Implement Heap Sort and Merge Sort by Oct 22

### ISSUE THREAD

**Issue by hassanabidpk** [DjangoGirlsSeoul/studygroup_2016#19]
**Algorithm 1** : 
- `Heap Sort`  
  Visualization : https://www.cs.usfca.edu/~galles/visualization/HeapSort.html  
  Book pages : `151p ~`
  한국어 : (?) https://www.acmicpc.net/problem/2220#
- `Merge Sort`
  Reference : https://www.khanacademy.org/computing/computer-science/algorithms/merge-sort/a/overview-of-merge-sort
  Hacker Rank :  https://www.hackerrank.com/challenges/ctci-merge-sort
  Book pages : `30~38p`

DEADLINE :  October 22 , 2016 

`한국어 도와 주실 수 있는분 구합니다.(1명) 연락주세요.`

**Comment by hassanabidpk** [comment]
Closing this! Hope everyone is done!

**Comment by mingrammer** [comment]
Merge sort is mentioned in 30~38p.
