### ISSUE TITLE
#1. 2016.10.09(sun)

### ISSUE THREAD

**Issue by downy158** [DjangoGirlsSeoul/studygroup_2016#20]
2016.10.09(sun)에 첫 모임을 진행합니다.
장소는 강남역 근처 메이아일랜드 입니다.
http://map.naver.com/?mapmode=0&lng=ee1892b402b4bef40313b4c2c160771b&pinId=36476425&pinType=site&lat=aabc7d08eb1c5f5dce75d1c850c48c98&dlevel=11&enc=b64
시간은 오후 1시~오후 3시입니다.

이번 모임의 내용은
1. 스터디 방식 공유
2. 장소예약 비용 관련 이야기
3. 불참 및 지각에 대한 관리(아무래도 스터디에 자주빠지시면 같이 공부하시는 분들의 의욕도 떨어지고 스터디 멤버들간의 약속을 깨는 것이기에 아주 중요한 문제입니다.)
4. 스터디 후기 포스팅 당부 ^^

불참/지각 하시는 분은 이슈에 댓글달아주세요.

**Comment by downy158** [comment]
ex. 송블루 / 불참 / 집안에 행사가 있어 참석 불가능합니다.
ex. 송북    / 참석 / 얼른 보고싶어요~
ex. 송블루북/ 지각 / 자격증 시험으로 인해 2시 도착 예정입니다.

**Comment by chiyodad** [comment]
박수석 / 참석 / 스터디 때 뵐게요!

**Comment by punkyoon** [comment]
하지윤 / 참석 / 반갑습니다.

**Comment by ghost** [comment]
홍미선 / 불참 / 가족모임이 있어 이번 주만 불참할께요~! 죄송합니다.

**Comment by AliceLiddell** [comment]
홍성남 / 참석 / 일요일에 봬요. 담주(실질적 스터디 1회차)는 제가 일본으로 떠나서 참석을 못합니다ㅜㅜ (미리 말씀드려야지)

**Comment by yklaus** [comment]
유성 / 불참 / 해커톤 참석으로 인해 부득이하게 불참하게 되었습니다. - 다음주에 봬요.

**Comment by sujinleeme** [comment]
이수진 / 지각 / 감기로 지각합니다.

**Comment by Jae-kwang** [comment]
정재광 / 참석 / 안녕하세요!

**Comment by downy158** [comment]
송다운 / 참석 / 반갑습니다~

**Comment by downy158** [comment]
송다운 / 참석 / 반갑습니다~

**Comment by amyKwon** [comment]
권예진 / 참석 / 일요일에 뵙겠습니다 :)

**Comment by magneticrose** [comment]
홍성남 / 참석 / 일요일에 봬요. 덧) 담주(16일)에 일본을 가야해서 실질적 1주차 스터디는 불참입니다 ㅠㅠ

**Comment by jheloper** [comment]
김중현 / 참석 / 일요일에 뵙겠습니다.

**Comment by aweekj** [comment]
조한주 / 참석 / 일요일에 봬요~

**Comment by MilenaLee** [comment]
이미현 / 불참 / 인적성시험이 겹쳐서 부득이하게 불참하게 되었숩니다ㅜ.ㅜ

**Comment by skycool7** [comment]
문명진/ 불참 / 외부행사 선약이 미리 되어 있어서 첫 모임만 불참입니다! 다음주에 만나요 :)

**Comment by hunylee** [comment]
이태헌/늦게라도 참석/ 교회 봉사가 2시에 끝나는데... 늦게라도 가겠습니다.

**Comment by hassanabidpk** [comment]
하산/ 참석 / 반갑습니다 `장고 개인 project 직업` 💯  🙈

**Comment by angie4u** [comment]
김은지/지각/빨리가겠습니다! 1시 30분정도에 도착할 예정입니다.

**Comment by chiyodad** [comment]
박수석 / 불참 / 감기가 심해서 다음주부터 참석하겠습니다

**Comment by hassanabidpk** [comment]
@downy158  You can close this issue now
