### ISSUE TITLE
#2. 2016.10.16(sun)

### ISSUE THREAD

**Issue by downy158** [DjangoGirlsSeoul/studygroup_2016#21]
2016.10.16(sun)에 두번째 진행합니다.
장소는 추후 공지드리겠습니다.
시간은 오후 1시~오후 3시입니다.

이번 모임의 내용은
1. 교재 배부
2. 간식비 - 15000원/10주 (현금으로 부탁드려요 ^^)
3. 팀별 모임 (분량은 추후 공지)
    1팀 책만 따라하는게 목표이다.
    2팀 책을 참고하여 내 프로젝트를 만든다.
    3팀 여럿이 모여서 프로젝트를 만든다.

불참/지각 하시는 분은 이슈에 댓글달아주세요.
또한, https://github.com/DjangoGirlsSeoul/studygroup_2016/tree/master/bluebook/README.md 에 이메일 추가부탁드립니다. 감사합니다.

**Comment by downy158** [comment]
송다운 / 참석 / 감기조심하시고 일요일에 봬요~

**Comment by amyKwon** [comment]
권예진/ 참석 / 일요일에 봬요 :)

**Comment by MilenaLee** [comment]
이미현 /  불참 / 이번주도 인적성 시험이 있습니다. 알고리즘 시험이라 떨리네욥..다음에 뵙겠습니다.

**Comment by aweekj** [comment]
조한주 / 참석 / 일요일에 봬요

**Comment by dodut** [comment]
양미림 / 참석 / >_< 기대됩니다!!!

**Comment by yklaus** [comment]
유성 / 참석 / 기대됩니다. 일요일에 봬요 ^^

**Comment by ghost** [comment]
홍미선 / 참석 / 꼭 갈께요 :)

**Comment by Jae-kwang** [comment]
정재광 / 참석 / 일요일에 봐요!

**Comment by Oliviaha** [comment]
하현주/참석/고고!

**Comment by sujinleeme** [comment]
이수진 / 참석 / 감사합니다 👍

**Comment by Saan2mari** [comment]
이지산/참석/감사합니다 ^^

**Comment by hunylee** [comment]
이태헌/참석/예배 끝나자마자 바로 갑니다.

**Comment by punkyoon** [comment]
하지윤/참석/안녕하세요

**Comment by jheloper** [comment]
김중현 / 참석 / 갑니다

**Comment by angie4u** [comment]
김은지/불참/감기가 심해서 못갈 것 같습니다. 다음주에 꼭 뵙겠습니다!

**Comment by skycool7** [comment]
문명진/참석/일요일에 만나요!!:)

**Comment by wengdiiiy** [comment]
안정민/불참/회사출근으로 불참합니당.. 죄송합니다
