### ISSUE TITLE
10월 23일(일) 세 번째 모임(2주차)

### ISSUE THREAD

**Issue by downy158** [DjangoGirlsSeoul/studygroup_2016#26]
이번주 일요일 세 번째 모임을 진행합니다.

장소 : 토즈 강남점(http://map.naver.com/?mapmode=0&lng=4bc3a12baa1016f56e72c39489efc838&pinId=11840366&pinType=site&lat=94de814a7a784ab1a23b63127c4c5e7c&dlevel=12&enc=b64)
시간 : 오후 1시~오후 3시(예약은 4시까지 해놓았으니 더 하고 가실 분들은 더 하셔도됩니다.)

참석여부를 토요일 오후 1시까지 comment로 알려주세요!(간식준비 및 장소 테이블 셋팅을 위해서 꼭 부탁드려요.)

**Comment by downy158** [comment]
송다운 / 참석 / 모델에 대해 공부하고 가겠습니다 ^^

**Comment by chiyodad** [comment]
박수석 / 참석 / 모델 깊이 알고 싶어요

**Comment by Oliviaha** [comment]
하현주/참석/어려워도 열씨미

**Comment by hassanabidpk** [comment]
하산 / 참석 / 장고 게인 project

**Comment by aweekj** [comment]
조한주 / 참석 / 간식이라니 두근두근

**Comment by jheloper** [comment]
김중현 / 참석 / 어서 공부해야겠네요

**Comment by onursahil** [comment]
오누르 / 참석 / 책 따라가기

**Comment by punkyoon** [comment]
하지윤 / 참석 / chapter3!

**Comment by ghost** [comment]
홍미선 / 참석 / 모델 잘 알고 싶어요~!

**Comment by Jae-kwang** [comment]
정재광 / 참석 / 공부해야지!

**Comment by AliceLiddell** [comment]
홍성남 / 불참 / 오늘 봐야하지만 아마 일요일에 출장을 갈 가능성이 높습니다. ㅠㅠ 계속 빠지게 되네요;;; 참석하게 되면 변경하겠습니다 ㅠㅠ

**Comment by angie4u** [comment]
김은지 / 참석 / 저번주에 못가서 너무 아쉬웠습니다!!

**Comment by yklaus** [comment]
유성/불참/개인사정으로 이번주는 참석이 힘들것 같습니다.

**Comment by amyKwon** [comment]
권예진 / 불참 / 딱 시간대 온라인 강의 중간고사 시험을 봅니다 ㅠㅠ

**Comment by mojosoeun** [comment]
이소은 / 참석 / 개인프로젝트 하러 갑니다~

**Comment by MilenaLee** [comment]
이미현 / 불참 / 마지막 인적성시험이 있습니다.. 다음주에 뵙겠습니다..!

**Comment by dodut** [comment]
양미림 / 참석 / 제가 전에 적었던것같은데...;; 다시 적습니닷!!

**Comment by sujinleeme** [comment]
이수진 / 참석 / 참석합니다!

**Comment by skycool7** [comment]
문명진/불참 또는 지각/지인 결혼식 참석때문에 스터디 참석이 어려울거 같습니다!만약 끝나고 늦게라도 참석할수 있을거 같으면 토즈로 가거나,못가게 되면 모델 파트 공부하고 슬랙창 스터디 내용 참고하겠습니다!

**Comment by magneticrose** [comment]
홍성남 / 참석 / 출장이 연기 됐습니다; 오후 1시까지였는데 바빠서 지금에서야 코멘트를 답니다. 위에 달았던 건 회사용 계정이었네요;;;

**Comment by wengdiiiy** [comment]
안정민/참석/내일뵙겠습니다^^

**Comment by hunylee** [comment]
헙! 작성한다는게 잊었네요.

이태헌/불참/개인적인 사정 때문에 어렵습니다. 다음주에 뵈어요
